version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: fedormityanin/yamdb_final:latest
    restart: always
    volumes:
      - static:/static
      - media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/www/static
      - media:/var/www/media
    ports:
      - "8080:80"
    depends_on:
      - web
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

